postgres:
  image: postgres:11.3-alpine
  ports:
    - 5432:5432
  restart: always
  environment:
    POSTGRES_DB: ccg-archive
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: password
  command:
    - "postgres"
    - "-c"
    - "listen_addresses=*"