# Generated by Django 3.0.5 on 2020-04-25 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('faction', models.CharField(choices=[('G', 'Government'), ('C', 'Corporate'), ('S', 'Street'), ('N', 'None')], max_length=50)),
                ('cost', models.IntegerField(blank=True, default=0, null=True)),
                ('abilities', models.CharField(max_length=150)),
                ('flavor', models.TextField(blank=True, max_length=500, null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(blank=True, default=False)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cyberpunk_ccg_archive.Card')),
                ('manual_security', models.IntegerField(default=0)),
                ('electronic_security', models.IntegerField(default=0)),
                ('production', models.IntegerField(default=0)),
                ('ops_points', models.IntegerField(default=0)),
                ('attributes', models.CharField(max_length=150)),
            ],
            bases=('cyberpunk_ccg_archive.card',),
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cyberpunk_ccg_archive.Card')),
                ('production', models.IntegerField(default=0)),
                ('victory', models.CharField(max_length=150)),
            ],
            bases=('cyberpunk_ccg_archive.card',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='./cards')),
                ('approved', models.BooleanField(blank=True, default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyberpunk_ccg_archive.Card')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
